import { Container, Stack, Title, Text } from '@mantine/core';
import { Header } from '../components/Header';
import { CarouselForm } from '../components/CarouselForm';
import { InstagramEmbed } from '../components/InstagramEmbed';

export default function CarouselPage() {
  return (
    <div style={{ minHeight: '100vh', paddingBottom: '2rem' }}>
      <Header />
      <Container size="md" px="md" pt="xl">
        <Stack gap={40}>
          <CarouselForm />
          <Stack gap="md" align="center" ta="center">
            <Title order={4}>Example carousel generated by Deckcreate</Title>
            <Text size="sm" c="dimmed" maw={480}>
              Frames and captions extracted directly from a YouTube video — no manual work required.
            </Text>
            <InstagramEmbed url="https://www.instagram.com/p/DU1pIOlj2Uf/" />
          </Stack>
        </Stack>
      </Container>
    </div>
  );
}
